version: '3'
services:
  duckling-service:
    image: rasa/duckling:latest
    ports:
    - "8000:8000"
    networks:
    - housebot-network
  action-service:
    image: housebot:latest
    ports:
    - "5055:5055"
    networks:
    - housebot-network
    command: bash -c "python3.7 -m rasa_sdk.endpoint --actions actions --cors "*" --debug"
  housebot-service:
    build: .
    image: housebot:latest
    ports:
    - "5000:5000"
    networks:
    - housebot-network
    depends_on:
    - action-service
    - duckling-service
    command: bash -c "python3.7 cmd_bot.py"
networks:
  housebot-network: